### ISSUE TITLE
System fails at clocks over 30 MHz.

### ISSUE THREAD

**Issue by TheRealTachyon** [terriblefire/tf530#1]
In digging through the schematics and datasheets for the project, I think it may be that the 74LVC1G17DBV Schmidt buffer may be getting pushed out of spec due to a combination of factors. 
The usage doesn't seem to fit the guidelines in the datasheet, and some of your comments during testing about heat, and one of the buffers failing and needed replaced seems to concur with my supposition.
I would guess that there might be three main issues.
- Lack of capacitors for power and ring protection
- current load under certain conditions (24ma is max)
- bus contention. (possibly fixed or reduced in recent firmware)

The last one seem particularly problematic as it can lead to overheating and device failure. I'm wondering if the CPLD programming or routing exposes one of the buffers to occasional bus contention, which leads to the overheating and eventual failure, depending on what the system and peripherals are doing. Higher frequencies would lead to more of these happening per unit of time. IE like a PWM of the line into bus contention. Fortunately the most recent software updates seem to have resolved at least some of these hits, potentially all, but it would be worth looking at on a scope or emulator.

**Comment by terriblefire** [comment]
The issue with the 30Mhz is simply the clock domain crossing method used is not able to cope with clock as far out as 7Mhz and 32Mhz. 

There is sufficient capacitors for the power supply. I have repeatedly shown this and it has been independently measured using commercial grade equipment.

Without measurements taken from a built board I am closing this.
