### ISSUE TITLE
Yellow screen on boot with A2000 and SupraRAM (6Mb) installed

### ISSUE THREAD

**Issue by gazsp** [terriblefire/tf530#10]
Using the Rev 2 TF530 in the CPU slot of the A2000 with a SupraRAM Zorro 2 card installed causes the Amiga to hang on boot with a yellow screen (exception thrown before software set up). I've reduced the amount of RAM on the board to 6Mb from 8Mb (as the TF530 maps it's 2Mb RAM in to the Zorro II address space). I've tried with 2, 4 and 6Mb of RAM, as well as different Zorro slots - the result is always the same.

Removing the TF530 (and replacing the 68000 CPU) allows the Amiga to boot fine in to Workbench, which shows 6Mb fast memory (which is correct). The Amiga boots fine using the TF530 without the SupraRAM installed.

SupraRAM details (probably not helpful):

http://www.bigbookofamigahardware.com/bboah/product.aspx?id=1078

**Comment by gazsp** [comment]
I'll be trying with the RC2 and RC3 firmware from here next: https://www.dropbox.com/s/uo5mcj0qjsqedwr/tf530_2018_01_15_RC2.zip?dl=0

I'm currently using mixed different bus / ram firmware at the moment.

**Comment by gazsp** [comment]
RC2 firmware shows screen corruption (this is a known issue I believe).

Anyway, going back to the mixed firmware and no SupraRAM for now - nothing else seems usable at the moment on the A2000.

**Comment by terriblefire** [comment]
For ZII Ram the max you can add after the 2Mb is 4Mb. Its just the way the AutoConfig picks the base addresses.

**Comment by kgc210** [comment]
I have the same board "Revision Unknown" on above link.
Jumpers set to 2MB Config and J3 set to R.
Results in board showing up in early start as RED defective board.
J3 set to T disables board and is not visible in Early Start.

Perhaps board is hard coded to start at address 200000?

**Comment by terriblefire** [comment]
If someone finds me an eBay link to a board I’ll debug after I get back from Arizona again

**Comment by kgc210** [comment]
There is one in Canada on ebay https://www.ebay.co.uk/itm/112826873891
But I personally don't think it's worthwhile pursuing.
Time and money would be better spent on pursuing AS7C38096A-10TIN?

That SupraCard uses odd and expensive 1Mx1 DRAM Chips

**Comment by terriblefire** [comment]
Already have 4 of those sitting ready to try. No time.

**Comment by terriblefire** [comment]
Not sure how feasible it is to say its a bug where two bits of hardware are incompatible.

**Comment by gazsp** [comment]
@terriblefire 

I'm in the UK - do you want me to post you my SupraRAM for testing? Maybe drop me an email at gaz@red-robot.co.uk with your details (also, I'm starting the 0xFE magazine and would like to interview you, so maybe just drop me an email anyway so I know where to contact you).

Anyway, I appreciate all your efforts so far - I'm happy to help out testing / providing you with as much help as I can.

@kgc210 

The SupraRAM works with an A2630 which has 4Mb of RAM on board in the Zorro 2 space (meaning that the SupraRAM memory isn't hardcoded to address 0x200000 - as the A2630 takes this address).

**Comment by terriblefire** [comment]
Happy to do this after the 17th of March. In America again for 10 days.

**Comment by gazsp** [comment]
No worries. Drop me an email whenever :-)

**Comment by terriblefire** [comment]
Anyone try this with caches disabled? CDIS jumper.. suspect that might change behaviour.
