### ISSUE TITLE
Add support for AS7C38096A-10TIN RAM Chips

### ISSUE THREAD

**Issue by kgc210** [terriblefire/tf530#11]
Using AS7C38096A-10TIN would allow for 4MB of 10ns SRAM.
Would require REV 3 board due to additional Address PIN and might need rearranging of allocated pins in Memory CPLD.

Datasheet states 3.3v (3.6v Max) but might be down-rated 5v part as per TF328 memory. Or would need Vcc pins isolating and tying to 3.3v regulator till a REV 3a? was generated?

I will try and perform experiments on them. @kgc210

**Comment by terriblefire** [comment]
Already Supported. Closed.

**Comment by terriblefire** [comment]
To be clear. The address pins exist on the REV3. The TF530 is specced at 2Mb but can use 5V chips double the size. User can try the 3.3V chips at their own risk,. I expect they'll die instantly,
