### ISSUE TITLE
Compact Flash > 4GB?

### ISSUE THREAD

**Issue by psyolent** [terriblefire/tf530#6]
Hi Stephen

Just a quick query - are CF cards > 4GB supported. Reason I ask is I have an 8GB SanDisk which works fine in my A1200, however in my A2000 with TF530 on adapter in the CPU daughter board slot, only my 4GB and 1GB CF cards work. 

The symptom I see is just a black screen and the HD activity light lit full on, on the CF --> IDE adapter.

Welcome your thoughts, 

Cheers

**Comment by mariuszk911** [comment]
This is operating system issue, not related to tf530. You need to update scsi.device in WB to see CF>4GB.

**Comment by psyolent** [comment]
.....i have a 3.1 ROM in my a2000 with an already updated scsi.device. even with 43.45 via loadmodule still having a 500MB boot partition it doesn't work with an 8GB SanDisk, which works fine in my A1200.

**Comment by terriblefire** [comment]
Card needs to be 3.3v compatible. The A1200 is 5V but the 328 is 3.3v.

**Comment by terriblefire** [comment]
Code in dev branch should fix all CF issues.
