### ISSUE TITLE
Atari ST compatibility?

### ISSUE THREAD

**Issue by ghoffart** [terriblefire/tf530#8]
Hi,

I’ve seen your demos on Youtube and got interested in having such a beauty in my machine. But it’s an Atari (1040STF), and although you demonstrated it partially on YT, I don’t find a lot to read about it here. Am I missing something or is there an obstacle?

Regards

**Comment by KimJorgensen** [comment]
According [to this](http://eab.abime.net/showthread.php?t=85380&page=113), you need TOS 2.06 and FastMEM and IDE don't work (yet)

**Comment by ghoffart** [comment]
Ah, I read that I should watch out for TF534S … thanks.
